### PR TITLE
Without resources

### PR DESCRIPTION
**Pull request by Cleggameg**
@leongersing
@mikelikesbikes

Redid challenge with all custom routes... would love feedback!!

Paul

### CODE REVIEW

**Comment by mikelikesbikes** [comment]
Can you close this? I'm doing some Github cleanup, and this appears in my default ["Pull Requests - Mentioned"](https://github.com/pulls/mentioned) view.

**Comment by mikelikesbikes** [comment]
@Cleggameg ^

**Comment by mikelikesbikes** [comment]
@Cleggameg thanks!

**Comment by Cleggameg** [comment]
No problem!!

**Pull request closed without merging**
